alias gits="git status"
alias gitb="git branch --remote && git branch"
alias gitn="git checkout -b"
alias gitc="git checkout"
alias gitd="git branch -d"
alias gitm="git checkout master && git remote prune origin && git pull"
alias gita="git add"
alias gita.="git add ."
