alias gis="git status"
alias gib="git branch --remote && git branch"
alias gin="git checkout -b"
alias gic="git checkout"
alias gid="git branch -d"
alias gim="git checkout master && git remote prune origin && git pull"
alias gia="git add"
alias gia.="git add ."
